# Generated by Django 4.0.3 on 2022-11-07 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('sigla', models.CharField(max_length=2, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Digite o título do seu imóvel', max_length=50)),
                ('descricao', models.TextField(help_text='Descreva seu imóvel', max_length=300, verbose_name='Descrição')),
                ('preco', models.DecimalField(decimal_places=2, help_text='Informe o preço de compra ou aluguel', max_digits=15, verbose_name='Preço do imóvel')),
                ('cep', models.CharField(help_text='Informe o CEP do imóvel', max_length=10, verbose_name='CEP')),
                ('rua', models.CharField(help_text='Informe a rua do imóvel', max_length=80)),
                ('bairro', models.CharField(help_text='Informe o bairro do imóvel', max_length=30)),
                ('numero', models.CharField(blank=True, help_text='Informe o número ou lote', max_length=30, null=True, verbose_name='Número')),
                ('quantidade_quartos', models.IntegerField(verbose_name='Quantidade de quartos')),
                ('quantidade_banheiros', models.IntegerField(verbose_name='Quantidade de banheiros')),
                ('area', models.DecimalField(decimal_places=2, help_text='Digite a área total do imóvel', max_digits=10, verbose_name='Área')),
                ('finalidade', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Vender'), (2, 'Alugar')], help_text='Informe a finalidade do imóvel', max_length=3)),
                ('cadastrado_em', models.DateTimeField(auto_now_add=True)),
                ('expira_em', models.DateTimeField()),
                ('publicado', models.BooleanField(default=False)),
                ('negociado', models.BooleanField(default=False)),
                ('destacado', models.BooleanField(default=False)),
                ('valor_pago_destaque', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('cidade', models.ForeignKey(help_text='Cidade do imóvel', on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Informe seu nome completo', max_length=100)),
                ('celular', models.CharField(help_text='Informe seu número de celular', max_length=12)),
                ('cpf', models.CharField(blank=True, help_text='Informe seu CPF', max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('cidade', models.ForeignKey(help_text='Informe a sua cidade', on_delete=django.db.models.deletion.PROTECT, to='cadastros.cidade')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movimentado_em', models.DateTimeField(auto_now_add=True)),
                ('pendente', models.BooleanField(default=True)),
                ('motivo', models.TextField()),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.imovel')),
                ('movimentado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo',
            field=models.ForeignKey(help_text='Informe o tipo do imóvel', on_delete=django.db.models.deletion.PROTECT, to='cadastros.tipo'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.imovel')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.estado'),
        ),
    ]
