# Generated by Django 4.0.3 on 2022-11-10 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='celular',
            field=models.CharField(help_text='Informe seu número de celular', max_length=16),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(default='123131321', help_text='Informe seu CPF', max_length=18, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
    ]
